name: gradle_properties
description: A dark package allowing to easily work with Gradle properties files.
version: 1.0.1
homepage: https://github.com/birjuvachhani/gradle_properties

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.3
  test: ^1.17.2
