name: gradle_properties
description: A dark package allowing to easily work with Gradle properties files.
version: 1.0.0
homepage: https://github.com/birjuvachhani/gradle_properties

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.17.2
