name: Coverage

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1
      - name: Dart SDK
        run: dart --version
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test
      - name: Install coverage package
        run: dart pub global activate coverage
      - name: Generate coverage report
        run: dart pub global run coverage:test_with_coverage
      - name: Generate lcov file
        run: dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --lcov -i coverage/coverage.json -o coverage/lcov.info
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info