name: Coverage

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
      - name: Install test_coverage
        run: pub global activate test_coverage
      - name: Generate Code Coverage
        run: pub global run test_coverage
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info