name: Coverage

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1
      - name: Dart SDK
        run: dart --version
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test
      - name: Install test_coverage
        run: dart pub global activate test_coverage
      - name: Generate Code Coverage
        run: dart pub global run test_coverage
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info