name: Build, Analyze & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Static Analysis
        run: dartanalyzer .
      - name: Run tests
        run: pub run test
      - name: Check Publish Warnings
        run: pub publish --dry-run