name: Code Quality

on: [push, pull_request]

jobs:
  quality:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image:  google/dart:2.7
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Analyzer
        run: dartanalyzer .
      - name: Dartfmt
        run: dartfmt --set-exit-if-changed -w --fix .