name: Tests

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test